{% set name = "wulffpack" %}
{% set version = "1.5" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/wulffpack-{{ version }}.tar.gz
  sha256: 96ebb2977e4f66e574a4256e1eeb565ac138847a15f3a60007d2d34fbeb63315

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
  run:
    - python >={{ python_min }}
    - ase
    - numpy >=1.12
    - scipy >=0.12.0
    - spglib
    - matplotlib-base

test:
  imports:
    - wulffpack
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://wulffpack.materialsmodeling.org
  license: MPL-2.0
  license_family: other
  license_file: LICENSE
  summary: A package for making Wulff constructions
  description: |
    WulffPack is a Python package for making Wulff constructions,
    typically for finding equilibrium shapes of nanoparticles.
    WulffPack constructs both continuum models and atomistic
    structures for further modeling with, e.g., molecular dynamics
    or density functional theory.
  doc_url: https://wulffpack.materialsmodeling.org
  dev_url: https://gitlab.com/materials-modeling/wulffpack

extra:
  recipe-maintainers:
    - jan-janssen
    - erhart1
