schema_version: 1

context:
  name: wulffpack
  version: "1.5"

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/wulffpack-${{ version }}.tar.gz
  sha256: 96ebb2977e4f66e574a4256e1eeb565ac138847a15f3a60007d2d34fbeb63315

build:
  number: 1
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python ${{ python_min }}.*
    - pip
    - setuptools
  run:
    - python >=${{ python_min }}
    - ase
    - numpy >=1.12
    - scipy >=0.12.0
    - spglib
    - matplotlib-base

tests:
  - python:
      imports:
        - wulffpack
      pip_check: true
      python_version:
        - ${{ python_min }}
        - "*"

about:
  license: MPL-2.0
  license_file: LICENSE
  summary: A package for making Wulff constructions
  description: |
    WulffPack is a Python package for making Wulff constructions,
    typically for finding equilibrium shapes of nanoparticles.
    WulffPack constructs both continuum models and atomistic
    structures for further modeling with, e.g., molecular dynamics
    or density functional theory.
  homepage: https://wulffpack.materialsmodeling.org
  repository: https://gitlab.com/materials-modeling/wulffpack
  documentation: https://wulffpack.materialsmodeling.org

extra:
  recipe-maintainers:
    - jan-janssen
    - erhart1
